use_frameworks!

target 'RSDropdownLib_Example' do
  pod 'RSDropdownLib', :path => '../'

  target 'RSDropdownLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
